# Generated by Django 5.0.1 on 2024-01-29 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('timer', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=models.Model, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
