# Generated by Django 5.0.1 on 2024-01-29 20:08

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_games_played_userprofile_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg_score',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('score'), '/', models.F('games_played')), output_field=models.PositiveIntegerField()),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['score'], name='accounts_us_score_1a0b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['avg_score'], name='accounts_us_avg_sco_24f300_idx'),
        ),
    ]
