# Generated by Django 5.0.1 on 2024-02-27 02:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=accounts.models.get_default_level
            ),
        ),
    ]
