# Generated by Django 5.0.1 on 2024-01-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_avg_score_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='accounts_us_avg_sco_24f300_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avg_score',
        ),
    ]
