# Generated by Django 5.0.1 on 2024-01-12 16:53

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='is_word',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length('guess'), 1), output_field=models.BooleanField()),
        ),
    ]
