# Generated by Django 5.0.1 on 2024-02-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamemap_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='next_turn_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='turns',
            field=models.JSONField(default=list),
        ),
    ]
