# Generated by Django 5.0.1 on 2024-01-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_guess_is_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='gamemap',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='guess',
            options={'ordering': ['game', 'created'], 'verbose_name_plural': 'guesses'},
        ),
    ]
