# Generated by Django 5.0.1 on 2024-01-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamemap_is_multiplayer_alter_gamemap_game_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
