# Generated by Django 5.0.1 on 2024-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamemap_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='timer',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
