# Generated by Django 5.0.1 on 2024-01-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_defaultgamesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultGameSettings',
        ),
    ]
