name: auto-format
on: pull_request
permissions:
  contents: write
jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Get changed python files
        id: changed-python-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **.py
          files_ignore: .github/**/*.yml
      - name: Get other changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **.css
            **.js
            **.html
            **.json
      - name: Format With Black
        uses: psf/black@stable
        if: steps.changed-python-files.outputs.any_changed == 'true'
        with:
          options: ''
          src: ${{ steps.changed-python-files.outputs.all_changed_files }}
      - name: Format with Prettier
        uses: actionsx/prettier@v2
        with:
          args: ${{ steps.changed-files.outputs.all_changed_files }} --write
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated formatting with black"
          git push