name: auto-format
on:
  schedule:
    # https://crontab.guru/every-night-at-midnight
    - cron: "0 7,9,12,14,16,18,20 * * *"
jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ruff
        uses: chartboost/ruff-action@v1
        with:
          args: . --fix --exit-zero
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}