name: Django Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
      - name: Create .env vars
        run: |
          cp .env.example .env
      - name: Run Tests
        run: |
          cd backend
          python manage.py test
